### ISSUE TITLE
Chrome dev tools/console doesn't seem to have a cookies viewer

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/cookies_and_sessions_readme#6]
Perhaps this text: If you open the developer console in your browser, you can see the cookies set by the current site. In Chrome's console, you can find this under Resources > Cookies. You can delete any cookie you like -- is from an earlier version? The tech coaches couldn't find it either and thought maybe it referred to an earlier version of Chrome?  Easy fix, just pull the EditThisCookie sentence above this one.

**Comment by cjbrock** [comment]
Hi @MiriamPeskowitz! We've updated the curriculum to reflect that there are certain extensions that you can now install in Chrome that allow you to edit cookies. Thank you for letting us know that our curriculum is outdated. 

// Corinna

**Comment by MiriamPeskowitz** [comment]
Hi Corinna! 

Thanks. Nice to be part of the process, and realize that I’ve learned enough to contribute along the way. 

Hope you’re well, 

Miriam 

On Aug 29, 2018, at 2:13 PM, Corinna Brock <notifications@github.com> wrote:

Hi @MiriamPeskowitz <https://github.com/MiriamPeskowitz>! We've updated the curriculum to reflect that there are certain extensions that you can now install in Chrome that allow you to edit cookies. Thank you for letting us know that our curriculum is outdated.

// Corinna
